"use client";

import { useEffect, useMemo, useState } from "react";
import type { BookingSlot } from "@/models/booking.model";
import { getCurrentProfile } from "@/services/auth.service";
import { supabase } from "@/lib/supabase";

type Mentor = { id: string; businessId: string; businessName: string; name: string; staffIds: string[] };
type Service = { id: string; name: string; duration?: string };
type Availability = { status: string; startDateTime: { dateTime: string }; endDateTime: { dateTime: string } };
type AvailabilityGroup = { staffId?: string; availabilityItems?: Availability[] };

function graphDate(value: string) { if (/(?:Z|[+-]\d{2}:?\d{2})$/.test(value)) return new Date(value); const [date, time = "00:00:00"] = value.split("T"); const [year, month, day] = date.split("-").map(Number); const [hour, minute, second = "0"] = time.split(":"); return new Date(Date.UTC(year, month - 1, day, Number(hour), Number(minute), Number(second))); }
function limaToUtc(value: Date) { return new Date(value.getTime() + 5 * 60 * 60 * 1000).toISOString(); }
function minutes(value?: string) { const match = value?.match(/^PT(?:(\d+)H)?(?:(\d+)M)?$/); return match ? Number(match[1] || 0) * 60 + Number(match[2] || 0) || 30 : 30; }
function slotsFor(item: Availability, index: number, duration: number, staffId?: string): BookingSlot[] {
  if (item.status.toLowerCase() !== "available") return [];
  const start = graphDate(item.startDateTime.dateTime).getTime();
  const end = graphDate(item.endDateTime.dateTime).getTime();
  const size = duration * 60000; const result: BookingSlot[] = [];
  for (let time = Math.ceil(Math.max(start, Date.now()) / size) * size; time + size <= end; time += size) {
    const date = new Date(time);
    result.push({ id: `${index}-${time}`, day: date.toLocaleDateString("es-PE", { weekday: "long", day: "numeric", month: "short", timeZone: "UTC" }), time: date.toLocaleTimeString("es-PE", { hour: "2-digit", minute: "2-digit", timeZone: "UTC" }), available: true, startAt: limaToUtc(date), endAt: limaToUtc(new Date(time + size)), staffId });
  }
  return result;
}

export default function MentorBooking() {
  const [mentors, setMentors] = useState<Mentor[]>([]); const [services, setServices] = useState<Service[]>([]); const [mentor, setMentor] = useState<Mentor>(); const [serviceId, setServiceId] = useState(""); const [slots, setSlots] = useState<BookingSlot[]>([]); const [selected, setSelected] = useState<BookingSlot>(); const [profile, setProfile] = useState({ name: "", email: "" }); const [loading, setLoading] = useState(true); const [loadingSlots, setLoadingSlots] = useState(false); const [error, setError] = useState(""); const [sending, setSending] = useState(false);
  const grouped = useMemo(() => slots.reduce<Record<string, BookingSlot[]>>((all, slot) => ((all[slot.day] ||= []).push(slot), all), {}), [slots]);

  useEffect(() => { void (async () => { const { data } = await supabase.auth.getUser(); if (!data.user) return; const { data: current } = await getCurrentProfile(data.user.id); if (current) setProfile({ name: [current.nombres, current.apellidos].filter(Boolean).join(" ") || current.email, email: current.email }); const response = await fetch("/api/mentors"); const list = response.ok ? await response.json() as Mentor[] : []; setMentors(list); setMentor(list[0]); setLoading(false); })(); }, []);
  useEffect(() => { if (!mentor) return; void (async () => { setLoadingSlots(true); setSlots([]); const serviceResponse = await fetch(`/api/bookings/services?businessId=${encodeURIComponent(mentor.businessId)}`); const list = serviceResponse.ok ? await serviceResponse.json() as Service[] : []; setServices(list); const service = list.find((item) => item.id === serviceId) || list[0]; if (service?.id !== serviceId) setServiceId(service?.id || ""); const response = await fetch("/api/bookings/availability", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId: mentor.businessId, staffIds: mentor.staffIds, startDateTime: new Date().toISOString(), endDateTime: new Date(Date.now() + 14 * 86400000).toISOString() }) }); if (response.ok) { const data = await response.json() as { value?: AvailabilityGroup[]; staffAvailabilityItem?: AvailabilityGroup[] }; const unique = new Map<string, BookingSlot>(); (data.value || data.staffAvailabilityItem || []).forEach((group) => (group.availabilityItems || []).flatMap((item, i) => slotsFor(item, i, minutes(service?.duration), group.staffId)).forEach((slot) => unique.set(`${slot.startAt}-${slot.endAt}`, slot))); setSlots([...unique.values()]); } setLoadingSlots(false); })(); }, [mentor, serviceId]);
  async function confirm() { if (!selected || !mentor || !serviceId || !selected.staffId) return; setSending(true); const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId: mentor.businessId, staffId: selected.staffId, serviceId, startAt: selected.startAt, endAt: selected.endAt, customerName: profile.name, customerEmail: profile.email }) }); setSending(false); if (!response.ok) { setError("No se pudo crear la reserva."); return; } setSelected(undefined); alert("Reserva confirmada"); }
  if (loading) return <main className="state-page"><p className="eyebrow">PROUNI · MENTORÍAS</p><h1>Cargando tu espacio...</h1></main>;
  return <div className="page-content"><section className="welcome-row"><div><p className="eyebrow">DISPONIBILIDAD EN TIEMPO REAL</p><h1>Elige con quién avanzar.</h1><p className="intro">Selecciona un mentor y revisa sus horarios disponibles.</p></div></section>{error && <p className="form-error">{error}</p>}{mentors.length === 0 ? <section className="empty-state"><h2>No hay mentores configurados</h2><p>Agrega personal a Microsoft Bookings para que aparezca aquí.</p></section> : <section className="mentor-picker">{mentors.map((item) => <button className="mentor-option" key={item.id} onClick={() => { setMentor(item); setError(""); }}><span className="mentor-avatar">{item.name.slice(0, 2).toUpperCase()}</span><span><strong>{item.name}</strong><small>{item.businessName}</small></span><b>Ver agenda →</b></button>)}</section>}{mentor && <section className="agenda-inline"><h2>Agenda de {mentor.name}</h2><label className="service-select">Tipo de reunión<select value={serviceId} onChange={(event) => setServiceId(event.target.value)}>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{loadingSlots ? <div className="empty-state compact-state"><h2>Cargando horarios...</h2></div> : <div className="day-groups">{Object.entries(grouped).map(([day, daySlots]) => <section className="day-group" key={day}><h3>{day}</h3><div className="day-slots">{daySlots.map((slot) => <button className="time-slot" key={slot.id} onClick={() => setSelected(slot)}>{slot.time}</button>)}</div></section>)}{!Object.keys(grouped).length && <div className="empty-state compact-state"><h2>No hay horarios disponibles</h2></div>}</div>}</section>}{selected && <div className="modal-backdrop"><div className="booking-modal"><button className="modal-close" onClick={() => setSelected(undefined)}>×</button><p className="eyebrow">NUEVA RESERVA</p><h2>Confirma tu sesión</h2><div className="booking-summary"><span>{selected.day}</span><strong>{selected.time}</strong><small>Microsoft Bookings · Lima</small></div><button className="primary-button" disabled={sending} onClick={() => void confirm()}>{sending ? "Reservando..." : "Confirmar reserva"}</button></div></div>}</div>;
}
